Document: telepathy-eri
Title: Debian telepathy-eri Manual
Author: <insert document author here>
Abstract: This manual describes what telepathy-eri is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/telepathy-eri/telepathy-eri.sgml.gz

Format: postscript
Files: /usr/share/doc/telepathy-eri/telepathy-eri.ps.gz

Format: text
Files: /usr/share/doc/telepathy-eri/telepathy-eri.text.gz

Format: HTML
Index: /usr/share/doc/telepathy-eri/html/index.html
Files: /usr/share/doc/telepathy-eri/html/*.html
